title: Vap'Mobile
baseurl: ""
color-scheme: "#4786B3" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - .htaccess
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag